name: engine_io_client
description: engine.io client
version: 0.0.1
author:
homepage:

dependencies:
  logging: any
  stream: any
  uuid: any
  utf: any
  web_socket_channel: any
  rxdart: any
  cookie_jar:
    git: https://github.com/flutterchina/cookie_jar.git

dev_dependencies:
  test: any

environment:
  sdk: "<=3.0.0"