name: engine_io_client
description: engine.io client
version: 0.0.1
author:
homepage:

dependencies:
  logging: any
  stream: any
  uuid: any
  utf: ^0.9.0+4
  web_socket_channel: ^1.0.7
  rxdart: any

dev_dependencies:
  test: any

environment:
  sdk: any

flutter:
  uses-material-design: true