name: socket_io_engine
description: socket.io engine
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  logging: any
  stream: any
  uuid: any
  built_value: ^5.2.1
  built_collection: ^3.0.5
  utf: ^0.9.0+4
  web_socket_channel: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.6.0
  built_value_generator: ^5.0.0
  source_gen: ^0.7.0
  test: any
  flutter_logger: ^0.0.1

flutter: