name: engine_io_client
description: engine.io client
version: 0.0.1
author: long1eu<home@long1.eu>
homepage:

dependencies:
  cookie_jar:
    git: https://github.com/flutterchina/cookie_jar.git

dev_dependencies:
  test: any

environment:
  sdk: '>=1.20.1 <3.0.0'