name: engine_io_client
description: engine.io client
version: 0.0.1
author:
homepage:

dependencies:
  stream: ^2.0.1+1
  uuid: ^1.0.3
  utf: ^0.9.0+4
  web_socket_channel: ^1.0.9
  cookie_jar:
    git: https://github.com/flutterchina/cookie_jar.git

dev_dependencies:
  test: any

environment:
  sdk: '>=1.20.1 <3.0.0'